image: docker.io/maven:3.8.3-openjdk-17

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn clean install -DskipTests
  cache:
    paths:
      - ./.m2/repository/

test:
  stage: test
  script:
    - mvn test
  cache:
    paths:
      - ./.m2/repository/
  artifacts:
    when: always
    reports:
      junit:
        - ./**/target/surefire-reports/TEST-*.xml
        - ./**/target/failsafe-reports/TEST-*.xml
