image: docker.io/maven:3.8.3-adoptopenjdk-11

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - build

build:
  stage: build
  script:
    - mvn clean install -DskipTests
  cache:
    paths:
      - ./.m2/repository/



